title = "Ethereum Improvement Proposals"
description = """\
Ethereum Improvement Proposals (EIPs & ERCs) describe standards for the \
Ethereum platform, such as core protocol changes and application-level \
standards.\
"""

theme = "eips-theme"

# `base_url` is required, but we set in build, so example.com is fine here.
base_url = "https://example.com/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "status", feed = true },
    { name = "category", feed = true },
    { name = "type", feed = true },
]

generate_feeds = true

[link_checker]
internal_level = "error"
external_level = "warn"

[markdown]

bottom_footnotes = true

[markdown.highlighting]
error_on_missing_language = true

style = "class"

light_theme = "github-light"
dark_theme = "github-dark"

extra_grammars = [
    "../syntaxes/abnf/ABNF.json",
    "../syntaxes/csl-json/CSL-JSON.json",
]

bottom_footnotes = true

[extra]
google_site_verification = "RgkqLC0fdJob232LgA5o7qUs7l1C3b2r1JKWcDlWOFI"
msvalidate = "E0C4C0C98D96DD251F246B52E434B0E9"

banner_taxonomies = [
    { label = "All", name = "status" },
]

banner_links = [
    { label = "Core", href = "/category/core/" },
    { label = "Networking", href = "/category/networking/" },
    { label = "Interface", href = "/category/interface/" },
    { label = "ERC", href = "/category/erc/" },
    { label = "Meta", href = "/type/meta/" },
    { label = "Informational", href = "/type/informational/" },
]

[extra.github]
eip_repository = "https://github.com/ethereum/EIPs"
erc_repository = "https://github.com/ethereum/ERCs"

[extra.taxonomies.status.stagnant]
tooltip = "This EIP had no activity for at least 6 months. This EIP should not be used."

[extra.taxonomies.status.withdrawn]
tooltip = "This EIP has been withdrawn, and should not be used."

[extra.taxonomies.status.draft]
tooltip = "This EIP is not yet recommended for general use or implementation, as it is subject to normative (breaking) changes."

[extra.taxonomies.status.review]
tooltip = "This EIP is not yet recommended for general use or implementation, as it is subject to normative (breaking) changes."

[extra.taxonomies.status.last-call]
tooltip = "This EIP is in the last call for review stage. The authors wish to finalize the EIP and ask you to provide feedback."

[extra.taxonomies.status.final]
tooltip = "This EIP is completed and no longer expected to change."

[extra.taxonomies.category.erc]
tooltip = "Application-level standards and conventions, including contract standards such as token standards, name registries, URI schemes, library/package formats, and wallet formats."

[extra.taxonomies.category.interface]
tooltip = "Improvements around client API/RPC specifications and standards, and also certain language-level standards like method names and contract ABIs."

[extra.taxonomies.category.networking]
tooltip = "Improvements around devp2p and Light Ethereum Subprotocol, as well as proposed improvements to network protocol specifications of whisper and swarm."

[extra.taxonomies.category.core]
tooltip = "Improvements requiring a consensus fork, as well as changes that are not necessarily consensus critical but may be relevant to “core dev” discussions."

[extra.taxonomies.type.informational]
tooltip = "Describes an Ethereum design issue, or provides general guidelines or information to the Ethereum community, but does not propose a new feature. Informational EIPs do not necessarily represent Ethereum community consensus or a recommendation, so users and implementers are free to ignore Informational EIPs or follow their advice."

[extra.taxonomies.type.meta]
tooltip = "Describes a process surrounding Ethereum or proposes a change to (or an event in) a process."

[extra.taxonomies.type.standards-track]
tooltip = "Describes any change that affects most or all Ethereum implementations or any application."
